export const journalCopy = {
  en: {
    label: "Wedding guides", title: "A little clarity,\nbefore the big day.",
    intro: "Practical notes on wedding films, budgets and planning a celebration in France. Start with the questions that matter to you.",
    read: "Read the guide", contents: "In this guide", related: "Keep planning",
    films: "Explore wedding films", service: "Wedding videography in Paris & France",
    cta: "Tell me about your celebration.",
    ctaCopy: "Send your date, venue or city, and what you would love to remember. We can take it from there.",
    contact: "Check your date", by: "By OTTO Vision"
  },
  fr: {
    label: "Conseils mariage", title: "Quelques repères,\navant le grand jour.",
    intro: "Des conseils pratiques sur les films de mariage, le budget et la préparation d’une célébration en France. Commencez par les questions qui vous concernent.",
    read: "Lire le guide", contents: "Dans ce guide", related: "Pour aller plus loin",
    films: "Découvrir les films de mariage", service: "Vidéaste de mariage à Paris et en France",
    cta: "Parlons de votre célébration.",
    ctaCopy: "Envoyez votre date, votre lieu ou votre ville et les souvenirs que vous souhaitez garder. Nous construirons la suite ensemble.",
    contact: "Vérifier votre date", by: "Par OTTO Vision"
  }
};

// Keep shared slugs so the existing language switch always reaches the paired guide.
// Add publication dates only when these guides actually go live.
export const guides = [
  {
    slug: "wedding-videography-budget-france", image: "/static/img/work/wedding-2025.jpg",
    project: "wedding-2025",
    en: {
      topic: "Budget", title: "How to plan your wedding videography budget in France",
      description: "Compare wedding film quotes by coverage, crew, sound, travel and deliverables, with a practical checklist for your enquiry.",
      intro: "A wedding film quote is easier to understand when you know what it covers. Start with the memories you want to keep, then compare proposals for the same brief. A headline price alone cannot tell you how much of your day will be filmed or what you will receive.",
      sections: [
        { id: "coverage", title: "Start with the moments you want filmed", paragraphs: ["Write down your priorities: getting ready, the ceremony, family, speeches or the first dance. Coverage from morning preparations to the evening asks for a different schedule from a ceremony and portrait session. If celebrations happen on several days, describe each separately.", "Give the videographer the locations as well as the times. Two preparations happening simultaneously in different places may require a second filmmaker, a revised schedule or a choice about which moments to cover."] },
        { id: "deliverables", title: "Compare the films, not just their length", paragraphs: ["A trailer, a highlight film and a longer ceremony edit serve different purposes. A short film can involve substantial work selecting footage, shaping the story, editing sound and refining colour. A longer running time is not, by itself, a measure of quality.", "Ask the quote to name each deliverable: approximate duration, format, whether speeches or the ceremony are included in full, and whether a vertical version is part of the package. Also clarify the delivery window and the scope of any revisions."] },
        { id: "logistics", title: "Make the practical costs visible", paragraphs: ["Ask whether travel, accommodation, additional hours and a second filmmaker are included or quoted separately. For a destination wedding, the locations and access arrangements help establish those costs before you book.", "Sound deserves its own conversation. If your vows or speeches are important to the film, ask how they will be recorded and what coordination is needed with the venue or sound team. Do not assume that every quote includes the same coverage or equipment."] },
        { id: "brief", title: "Send a brief that makes quotes comparable", paragraphs: ["Use the same brief when approaching different videographers. Compare both the films you connect with and the written scope. OTTO Vision defines coverage and deliverables around the celebration; send your plans to discuss availability and a proposal."], bullets: ["Wedding date, venue or city, and any additional celebration days.", "Approximate start and finish times, with travel between venues.", "The moments and people you most want included.", "Preferred films: trailer, highlights, ceremony or speeches.", "Your working budget and any priorities you could adjust."] }
      ]
    },
    fr: {
      topic: "Budget", title: "Quel budget prévoir pour un vidéaste de mariage en France ?",
      description: "Comparez les devis de films de mariage : durée de présence, équipe, son, déplacements et livrables. Une liste pratique pour préparer votre demande.",
      intro: "Un devis de film de mariage devient plus clair lorsqu’on sait ce qu’il comprend. Partez des souvenirs que vous souhaitez garder, puis comparez les propositions à partir du même besoin. Un prix seul ne dit ni quelle partie de la journée sera filmée ni ce qui vous sera livré.",
      sections: [
        { id: "coverage", title: "Commencez par les moments à filmer", paragraphs: ["Notez vos priorités : préparatifs, cérémonie, famille, discours ou première danse. Une présence du matin à la soirée demande une organisation différente d’une cérémonie suivie de portraits. Si les festivités durent plusieurs jours, décrivez chaque journée séparément.", "Précisez les lieux autant que les horaires. Deux préparatifs simultanés à des endroits différents peuvent nécessiter un second vidéaste, un programme adapté ou un choix sur les moments à couvrir."] },
        { id: "deliverables", title: "Comparez les films, pas seulement leur durée", paragraphs: ["Une bande-annonce, un film essentiel et un montage long de cérémonie répondent à des usages différents. Un film court peut demander un travail important de sélection, de narration, de montage sonore et d’étalonnage. Une durée plus longue ne mesure pas, à elle seule, la qualité.", "Demandez que chaque livrable soit précisé : durée indicative, format, présence des discours ou de la cérémonie en intégralité et éventuelle version verticale. Clarifiez aussi le délai de livraison et les modifications comprises."] },
        { id: "logistics", title: "Rendez les frais pratiques visibles", paragraphs: ["Vérifiez si les déplacements, l’hébergement, les heures supplémentaires et un second vidéaste sont inclus ou facturés séparément. Pour un mariage à destination, les lieux et leurs conditions d’accès permettent d’anticiper ces frais.", "Le son mérite une discussion à part entière. Si vos vœux ou les discours comptent pour vous, demandez comment ils seront enregistrés et quelle coordination prévoir avec le lieu ou l’équipe son. Tous les devis ne couvrent pas nécessairement les mêmes prestations."] },
        { id: "brief", title: "Envoyez un brief qui facilite la comparaison", paragraphs: ["Transmettez les mêmes informations aux vidéastes consultés. Comparez les films qui vous touchent et le périmètre écrit de chaque proposition. OTTO Vision définit la couverture et les livrables autour de votre célébration : partagez votre projet pour discuter des disponibilités et d’une proposition."], bullets: ["Date, lieu ou ville et éventuelles journées supplémentaires.", "Horaires approximatifs de début et de fin, avec les trajets.", "Moments et personnes que vous souhaitez retrouver dans le film.", "Films souhaités : bande-annonce, film essentiel, cérémonie ou discours.", "Budget envisagé et priorités que vous pourriez ajuster."] }
      ]
    }
  },
  {
    slug: "choosing-your-wedding-videographer", image: "/static/img/work/wedding-2023-stairs.jpg",
    project: "wedding-2023",
    en: {
      topic: "Choosing your filmmaker", title: "Questions to ask before booking a wedding videographer",
      description: "Look beyond a showreel: questions about complete films, sound, filming style, delivery and practical arrangements before booking.",
      intro: "The right wedding videographer should make sense both on screen and in conversation. Beautiful images matter, but so do the way the day feels, the words you want to hear again and a clear understanding of the finished films.",
      sections: [
        { id: "films", title: "Can we watch complete wedding films?", paragraphs: ["A showreel gathers a filmmaker’s strongest images. Complete films show how a story develops, how sound works with music and whether the pace holds your attention. Watch more than one, preferably including a celebration with a similar setting or atmosphere to yours.", "Notice what you respond to: intimate exchanges, a lively evening, careful portraits or the sound of the ceremony. Explain that preference using specific moments instead of asking someone to copy another filmmaker’s work."] },
        { id: "presence", title: "How will you work with us on the day?", paragraphs: ["Ask how much direction to expect, whether dedicated portrait time is useful and how the videographer works alongside your photographer. If you feel uncomfortable in front of a camera, say so early: the answer should help you picture the experience.", "OTTO Vision’s approach combines discreet observation with considered portraits. Planning can take place in English, French or Chinese. Discuss the balance you want between time with your guests and time set aside for filming."] },
        { id: "sound", title: "How are voices and important moments recorded?", paragraphs: ["Tell the filmmaker whether vows, speeches or family voices are essential to you. Ask about microphones, venue restrictions and coordination with the sound team. A beautiful ceremony image does not tell you how the words were captured.", "Also ask how footage is backed up, how long files are retained and what happens if illness or equipment problems disrupt the plan. These are questions to agree with your provider, not assumptions about a standard package."] },
        { id: "agreement", title: "What exactly are we agreeing to?", paragraphs: ["Before booking, check that the proposal reflects your conversation. Clarify the filming hours, number of filmmakers, deliverables, delivery window and revision process. Discuss music preferences and how suitable licensed music will be selected.", "Ask how your film may be shared publicly and explain any privacy preferences. Keep a written record of the agreed scope so that you and the filmmaker can prepare for the same day."], bullets: ["Which dates and locations are covered?", "What is included, and what would cost extra?", "What films and file formats will we receive?", "When should we expect delivery, and how are changes handled?", "What are the payment and cancellation terms?"] }
      ]
    },
    fr: {
      topic: "Choisir son vidéaste", title: "Les questions à poser avant de réserver un vidéaste de mariage",
      description: "Au-delà du showreel : les questions à poser sur les films complets, le son, l’approche, la livraison et l’organisation du mariage.",
      intro: "Le bon vidéaste de mariage doit vous convaincre à l’image comme dans l’échange. Les belles images comptent, mais aussi la façon de vivre la journée, les paroles que vous souhaitez réentendre et une idée claire des films que vous recevrez.",
      sections: [
        { id: "films", title: "Pouvons-nous regarder des films de mariage complets ?", paragraphs: ["Un showreel rassemble les images les plus marquantes d’un réalisateur. Les films complets montrent comment le récit se construit, comment le son accompagne la musique et si le rythme vous touche jusqu’au bout. Regardez-en plusieurs, dont une célébration proche de votre ambiance ou de votre cadre.", "Repérez ce qui vous plaît : échanges intimes, soirée animée, portraits soignés ou paroles de la cérémonie. Appuyez-vous sur des passages précis pour expliquer vos goûts, sans demander de reproduire le travail d’un autre vidéaste."] },
        { id: "presence", title: "Comment travaillerez-vous avec nous le jour J ?", paragraphs: ["Demandez quelle place prend la direction, s’il est utile de prévoir un temps pour les portraits et comment le vidéaste collabore avec le photographe. Si vous êtes peu à l’aise devant une caméra, dites-le tôt : la réponse doit vous aider à imaginer l’expérience.", "L’approche d’OTTO Vision associe observation discrète et portraits réfléchis. La préparation peut se faire en français, en anglais ou en chinois. Échangez sur l’équilibre souhaité entre le temps avec vos invités et celui consacré aux images."] },
        { id: "sound", title: "Comment les voix et les moments importants sont-ils enregistrés ?", paragraphs: ["Précisez si les vœux, les discours ou les voix de vos proches sont essentiels pour vous. Posez des questions sur les micros, les restrictions du lieu et la coordination avec l’équipe son. Une belle image de cérémonie ne renseigne pas sur la prise de son.", "Demandez aussi comment les images sont sauvegardées, combien de temps les fichiers sont conservés et ce qui est prévu en cas de maladie ou de problème matériel. Ce sont des points à convenir avec votre prestataire, pas des prestations à supposer incluses."] },
        { id: "agreement", title: "Sur quoi nous mettons-nous d’accord ?", paragraphs: ["Avant de réserver, vérifiez que la proposition reflète votre échange : heures de présence, nombre de vidéastes, livrables, délai de livraison et modifications. Discutez de vos goûts musicaux et du choix d’une musique adaptée avec les droits nécessaires.", "Demandez comment le film pourra être diffusé publiquement et exprimez vos préférences de confidentialité. Gardez une trace écrite du périmètre convenu afin de préparer la même journée."], bullets: ["Quels jours et quels lieux sont couverts ?", "Qu’est-ce qui est inclus et qu’est-ce qui serait en supplément ?", "Quels films et formats recevrons-nous ?", "Quel délai prévoir et comment les modifications sont-elles traitées ?", "Quelles sont les conditions de paiement et d’annulation ?"] }
      ]
    }
  },
  {
    slug: "wedding-day-film-timeline", image: "/static/img/work/wedding-2024-window.jpg",
    project: "wedding-2024",
    en: {
      topic: "The wedding day", title: "A wedding day timeline that leaves room for a natural film",
      description: "Plan preparations, ceremony sound, portraits and the evening with room for real moments and practical travel buffers.",
      intro: "A natural wedding film starts with a workable day. The aim is not to turn your celebration into a production schedule, but to give important moments enough space to happen without rushing. Build the plan around your ceremony, your guests and the places you will use.",
      sections: [
        { id: "preparations", title: "Give the morning a little breathing room", paragraphs: ["Share where each of you will get ready and who will be there. If the locations are separate, decide with your filmmaker how to cover them. Allow for finishing touches, time with family and the departure, rather than scheduling every image for the final few minutes.", "Choose a comfortable preparation space with usable light where possible. Keep everyday clutter to one side, but leave room for the people and objects that belong to your day. You do not need a room that looks like a studio."] },
        { id: "ceremony", title: "Plan arrivals and sound before the ceremony", paragraphs: ["Include the actual journey between locations, parking and access time. Share any ceremony rules with the photographer and videographer in advance. They may need time to choose positions and coordinate microphones before guests settle in.", "Confirm who is speaking and whether there will be music or readings. Last-minute surprises can be lovely for guests, but telling the filming team privately helps them prepare for the moment."] },
        { id: "portraits", title: "Make portrait time realistic", paragraphs: ["Choose one or two nearby settings rather than a long list of stops. For portraits in Paris, travel and crowds can take time away from the celebration. A short, relaxed walk close to the venue can offer more usable moments than a rushed tour of landmarks.", "Discuss the light for your date and the spaces actually available. If outdoor portraits matter to you, keep an indoor alternative for rain. Agree the timing with your photographer and planner so that both teams can work without repeatedly taking you away from guests."] },
        { id: "evening", title: "Give speeches and the evening a clear place", paragraphs: ["Tell the filmmaker when speeches and the first dance are expected, and ask a designated person to flag changes. Check that these moments fall within the coverage you have booked. Leave some flexibility if dinner or the ceremony runs late.", "Use the following order as a planning conversation, not a fixed timetable. Exact durations should follow your locations, traditions and priorities."], bullets: ["Preparations, family moments and departure.", "Travel buffer, arrivals and ceremony setup.", "Ceremony, congratulations and time with guests.", "A shared portrait window for photo and film.", "Dinner, speeches, first dance and celebration within the agreed coverage."] }
      ]
    },
    fr: {
      topic: "Le jour J", title: "Un planning de mariage qui laisse vivre un film naturel",
      description: "Organisez préparatifs, son de cérémonie, portraits et soirée en gardant du temps pour les vrais moments et les déplacements.",
      intro: "Un film de mariage naturel commence par une journée bien pensée. L’objectif est de laisser les moments importants se vivre sans précipitation. Construisez le programme autour de votre cérémonie, de vos invités et des lieux que vous utiliserez.",
      sections: [
        { id: "preparations", title: "Laissez respirer les préparatifs", paragraphs: ["Indiquez où chacun se prépare et avec qui. Si les lieux sont séparés, décidez avec votre vidéaste de la façon de les couvrir. Prévoyez les dernières touches, un moment en famille et le départ, plutôt que de concentrer toutes les images sur les dernières minutes.", "Si possible, choisissez une pièce confortable avec une lumière exploitable. Mettez le désordre quotidien de côté tout en gardant la place des personnes et des objets qui font partie de votre journée. La pièce n’a pas besoin de ressembler à un studio."] },
        { id: "ceremony", title: "Anticipez les arrivées et le son de la cérémonie", paragraphs: ["Intégrez le trajet réel, le stationnement et l’accès aux lieux. Transmettez les règles de la cérémonie au photographe et au vidéaste en amont. Ils peuvent avoir besoin de temps pour choisir leurs positions et préparer les micros avant l’installation des invités.", "Confirmez les intervenants, les musiques et les lectures prévues. Une surprise peut rester une surprise pour les invités tout en étant annoncée discrètement à l’équipe image pour qu’elle puisse s’y préparer."] },
        { id: "portraits", title: "Prévoyez des portraits réalistes", paragraphs: ["Choisissez un ou deux endroits proches plutôt qu’une longue liste d’étapes. À Paris, les trajets et l’affluence peuvent réduire votre temps de célébration. Une courte promenade détendue près du lieu peut offrir davantage de moments qu’un circuit précipité entre monuments.", "Discutez de la lumière à votre date et des espaces disponibles. Si les portraits extérieurs comptent pour vous, prévoyez une solution intérieure en cas de pluie. Accordez le créneau avec le photographe et la personne qui coordonne le mariage pour éviter de vous éloigner plusieurs fois des invités."] },
        { id: "evening", title: "Donnez une place claire aux discours et à la soirée", paragraphs: ["Annoncez les horaires prévus des discours et de la première danse, et désignez une personne pour signaler les changements. Vérifiez que ces moments entrent dans la couverture réservée. Gardez de la souplesse si le dîner ou la cérémonie prend du retard.", "L’enchaînement suivant sert de base de discussion, pas de planning imposé. Les durées doivent suivre vos lieux, vos traditions et vos priorités."], bullets: ["Préparatifs, moments en famille et départ.", "Marge de trajet, arrivées et installation pour la cérémonie.", "Cérémonie, félicitations et temps avec les invités.", "Créneau de portraits commun à la photo et au film.", "Dîner, discours, première danse et fête selon la couverture convenue."] }
      ]
    }
  },
  {
    slug: "planning-destination-wedding-film-france", image: "/static/img/wedding/wedding-25.jpg",
    project: "wedding-2023",
    en: {
      topic: "Destination weddings", title: "Planning your wedding film in France from abroad",
      description: "A practical guide for international couples: plan languages, locations, ceremony details and your filming brief before travelling to France.",
      intro: "You do not need to be in France for every planning conversation. A clear brief, shared contacts and a realistic schedule give your filmmaker a useful picture of the celebration before you arrive. Begin with the date and location, then build the details together.",
      sections: [
        { id: "brief", title: "Begin with one shared brief", paragraphs: ["Send the wedding date, the venue or shortlist, the approximate guest count and any events on other days. Explain whether you imagine a quiet gathering, a lively celebration or a mix of both. A few film references can help communicate tone, but your own priorities should lead.", "Keep the current schedule and supplier contacts in a single shared document. Mark provisional items clearly and agree who will send updates. This reduces conflicting versions when several people are planning across time zones."] },
        { id: "languages", title: "Talk about languages and traditions early", paragraphs: ["OTTO Vision can plan with you in English, French or Chinese. Tell us which languages will be spoken during the ceremony and speeches, and which words you particularly want preserved. Agree whether translation or subtitles are needed as part of the requested deliverables.", "Explain any traditions or family moments that the filmmaker may not know. Describe who is involved, what is likely to happen and whether there are restrictions on filming. A short explanation before the wedding helps the camera be ready without interrupting the moment."] },
        { id: "venue", title: "Connect the venue, planner and filming team", paragraphs: ["Arrange a direct introduction to your venue contact or wedding planner. Ask about access, ceremony rules, power, sound equipment and indoor alternatives for rain. If there are several locations, share addresses and realistic travel times.", "For a château celebration outside Paris, discuss travel and accommodation as part of the proposal. For city portraits, consider how far you really want to travel on the wedding day. Confirm any location permissions with the venue or relevant operator before building the schedule around them."] },
        { id: "handover", title: "Confirm the plan before you travel", paragraphs: ["Arrange a final conversation once the main timings are settled. Confirm the people to contact on the day, planned surprises, coverage hours and the agreed films. Discuss music, privacy preferences and delivery expectations while there is time to resolve questions.", "A simple first enquiry is enough to begin: your date, venue or city, preferred language and the moments that matter most. If the venue is still undecided, say so; the filming plan can develop alongside the celebration."], bullets: ["Latest schedule, including travel and additional events.", "Venue, planner and on-the-day contact details.", "Languages, traditions and important speakers.", "Agreed coverage, deliverables and practical arrangements.", "Weather alternative and any filming restrictions."] }
      ]
    },
    fr: {
      topic: "Mariage à destination", title: "Préparer son film de mariage en France depuis l’étranger",
      description: "Un guide pour les couples internationaux : langues, lieux, cérémonie et brief de tournage à préparer avant votre arrivée en France.",
      intro: "Il n’est pas nécessaire d’être en France pour chaque échange de préparation. Un brief clair, des contacts partagés et un programme réaliste permettent au vidéaste de comprendre votre célébration avant votre arrivée. Commencez par la date et le lieu, puis construisez les détails ensemble.",
      sections: [
        { id: "brief", title: "Commencez par un brief commun", paragraphs: ["Envoyez la date, le lieu ou votre sélection de lieux, le nombre approximatif d’invités et les éventuelles festivités sur plusieurs jours. Expliquez si vous imaginez une rencontre intime, une fête animée ou les deux. Quelques références peuvent préciser l’ambiance, mais vos propres priorités doivent guider le projet.", "Gardez le programme à jour et les contacts des prestataires dans un seul document partagé. Signalez les éléments provisoires et convenez de la personne qui transmet les mises à jour. Cela limite les versions contradictoires lorsque l’organisation se fait sur plusieurs fuseaux horaires."] },
        { id: "languages", title: "Parlez tôt des langues et des traditions", paragraphs: ["OTTO Vision peut préparer votre projet en français, en anglais ou en chinois. Précisez les langues de la cérémonie et des discours, ainsi que les paroles que vous souhaitez particulièrement garder. Convenez d’une éventuelle traduction ou de sous-titres parmi les livrables demandés.", "Expliquez les traditions ou les moments familiaux que le vidéaste pourrait ne pas connaître : qui participe, ce qui va se passer et les restrictions éventuelles. Une courte explication avant le mariage permet d’être prêt sans interrompre le moment."] },
        { id: "venue", title: "Mettez en relation le lieu, l’organisation et l’équipe image", paragraphs: ["Présentez directement votre contact sur le lieu ou votre wedding planner au vidéaste. Échangez sur les accès, les règles de cérémonie, l’électricité, le matériel son et les solutions intérieures en cas de pluie. Si plusieurs lieux sont prévus, partagez les adresses et des temps de trajet réalistes.", "Pour une célébration dans un château hors de Paris, abordez les déplacements et l’hébergement dans la proposition. Pour des portraits en ville, réfléchissez aux trajets que vous souhaitez vraiment faire le jour J. Confirmez les autorisations nécessaires auprès du lieu ou de son gestionnaire avant de fixer le programme."] },
        { id: "handover", title: "Confirmez le programme avant votre départ", paragraphs: ["Prévoyez un dernier échange lorsque les principaux horaires sont fixés. Confirmez les contacts du jour, les surprises prévues, les heures de présence et les films convenus. Parlez de musique, de confidentialité et de livraison tant qu’il reste du temps pour clarifier les questions.", "Pour commencer, une demande simple suffit : votre date, votre lieu ou votre ville, votre langue préférée et les souvenirs essentiels pour vous. Si le lieu n’est pas encore choisi, indiquez-le ; la préparation du film peut avancer avec celle du mariage."], bullets: ["Dernier programme, trajets et événements supplémentaires inclus.", "Contacts du lieu, de l’organisation et du jour J.", "Langues, traditions et intervenants importants.", "Couverture, livrables et dispositions pratiques convenus.", "Solution en cas de pluie et restrictions de tournage."] }
      ]
    }
  }
];

export function getGuides(locale = "en") {
  return guides.map(({ en, fr, ...guide }) => ({ ...guide, ...(locale === "fr" ? fr : en) }));
}

export function getGuide(locale, slug) {
  return getGuides(locale).find((guide) => guide.slug === slug);
}
